"""property del title

Revision ID: 067b16439176
Revises: f43690e52e1c
Create Date: 2025-12-09 16:08:34.249845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '067b16439176'
down_revision: Union[str, Sequence[str], None] = 'f43690e52e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
