"""None unique adress

Revision ID: 09ab409c69be
Revises: 4824b773c4d2
Create Date: 2026-01-14 16:59:25.034132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ab409c69be'
down_revision: Union[str, Sequence[str], None] = '4824b773c4d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('properties_address_key'), 'properties', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('properties_address_key'), 'properties', ['address'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
