"""client fix

Revision ID: 0d707901956e
Revises: 233c87e5bdcc
Create Date: 2025-12-05 16:36:26.575162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d707901956e'
down_revision: Union[str, Sequence[str], None] = '233c87e5bdcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'properties_count')
    op.drop_column('clients', 'appointments_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('appointments_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('clients', sa.Column('properties_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
