"""Fix document relationships

Revision ID: 15821de345b9
Revises: 81f25c8689d9
Create Date: 2025-12-13 21:28:29.021089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15821de345b9'
down_revision: Union[str, Sequence[str], None] = '81f25c8689d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_documents_created_at'), 'documents', ['created_at'], unique=False)
    op.drop_constraint(op.f('documents_client_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_uploaded_by_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_deal_id_fkey'), 'documents', type_='foreignkey')
    op.drop_constraint(op.f('documents_property_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['uploaded_by'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'deals', ['deal_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'properties', ['property_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'documents', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_property_id_fkey'), 'documents', 'properties', ['property_id'], ['id'])
    op.create_foreign_key(op.f('documents_deal_id_fkey'), 'documents', 'deals', ['deal_id'], ['id'])
    op.create_foreign_key(op.f('documents_uploaded_by_fkey'), 'documents', 'users', ['uploaded_by'], ['id'])
    op.create_foreign_key(op.f('documents_client_id_fkey'), 'documents', 'clients', ['client_id'], ['id'])
    op.drop_index(op.f('ix_documents_created_at'), table_name='documents')
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
