"""fix dependency

Revision ID: 233c87e5bdcc
Revises: 2d0b40dccf7d
Create Date: 2025-12-03 18:02:16.459126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233c87e5bdcc'
down_revision: Union[str, Sequence[str], None] = '2d0b40dccf7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('type', sa.Enum('ЗАВЕРШЕНО', 'ОПЛАЧЕНО', 'ОТМЕНЕНО', 'АКТИВНО', name='dealtype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'type')
    # ### end Alembic commands ###
