"""add client del property from user 

Revision ID: 40d0492f5e8a
Revises: 8d256d9c66f1
Create Date: 2025-11-07 16:33:36.372169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40d0492f5e8a'
down_revision: Union[str, Sequence[str], None] = '8d256d9c66f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'clients', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('deals_user_id_fkey'), 'deals', type_='foreignkey')
    op.create_foreign_key(None, 'deals', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('properties_user_id_fkey'), 'properties', type_='foreignkey')
    op.drop_column('properties', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('properties_user_id_fkey'), 'properties', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.create_foreign_key(op.f('deals_user_id_fkey'), 'deals', 'clients', ['user_id'], ['id'])
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'user_id')
    # ### end Alembic commands ###
