"""Add photos field to properties

Revision ID: 4824b773c4d2
Revises: 0719376208e7
Create Date: 2025-12-22 17:26:28.567616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4824b773c4d2'
down_revision: Union[str, Sequence[str], None] = '0719376208e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('photos', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'photos')
    # ### end Alembic commands ###
