"""Add fixed_payment to deals

Revision ID: 8b9664fa1d21
Revises: a0ed4f9a4826
Create Date: 2025-12-12 21:06:49.914199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b9664fa1d21'
down_revision: Union[str, Sequence[str], None] = 'a0ed4f9a4826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('fixed_payment', sa.Float(), server_default=sa.text('0.0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'fixed_payment')
    # ### end Alembic commands ###
