"""minor fix

Revision ID: dacbd2addef8
Revises: 40d0492f5e8a
Create Date: 2025-11-07 16:42:48.206940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacbd2addef8'
down_revision: Union[str, Sequence[str], None] = '40d0492f5e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('interactions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interactions', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('appointments', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
